name: Deploy React App to FTP Server

on:
  push:
    branches:
      - main  # Trigger deployment on every push to the `main` branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (for React build process)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # Update this to match your Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the React app
      - name: Build the React app
        run: npm run build

      # Step 5: Deploy to FTP Server
      - name: Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}  # FTP server URL
          username: ${{ secrets.FTP_USERNAME }}  # FTP username
          password: ${{ secrets.FTP_PASSWORD }}  # FTP password
          local-dir: ./build  # React build folder
